import type { components } from "@/lib/api/schema"

type Schemas = components["schemas"]

export type Drink = Schemas["Drink"]
export type DrinkCard = Schemas["DrinkCard"]
export type DrinkPage = Schemas["DrinkPage"]
export type DrinkFacets = Schemas["DrinkFacets"]
export type FlavorDna = Schemas["FlavorDna"]
export type Suggestion = Schemas["Suggestion"]
export type TasteProfile = Schemas["TasteProfile"]
export type TasteShare = Schemas["TasteShare"]
export type TasteCompatibility = Schemas["TasteCompatibility"]
export type Reaction = Schemas["ReactRequest"]["reaction"]
export type CocktleGame = Schemas["CocktleGame"]
export type CocktleGuess = Schemas["CocktleGuess"]
export type CocktleMode = Schemas["CocktleGame"]["mode"]
export type Plan = Schemas["Plan"]
export type Payment = Schemas["Payment"]
export type MySubscription = Schemas["MySubscription"]
export type Venue = Schemas["Venue"]
export type VenueMenu = Schemas["VenueMenu"]
export type InventoryItem = Schemas["InventoryItem"]
export type Mood = Schemas["Mood"]
export type PantrySuggestions = Schemas["PantrySuggestions"]
